version: '3'

services:
  db:
    image: 'mongo'
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=secret_service
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1221iroot
    volumes:
      - ./db_init.js:/docker-entrypoint-initdb.d/db_init.js

    ports:
      - '27017-27019:27017-27019'

  web:
    build: .
    container_name: 'fastapi'
    command: uvicorn app.main:app --workers 4 --host 0.0.0.0
    depends_on:
      - db
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_USER=taori
      - MONGO_PASSWORD=iroat1221
      - MONGO_DB=secret_service
    ports:
      - '8000:8000'
